// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// BinaryOperandsRequest defines model for BinaryOperandsRequest.
type BinaryOperandsRequest struct {
	A float64 `json:"a"`
	B float64 `json:"b"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// PowerRequest defines model for PowerRequest.
type PowerRequest struct {
	Base     float64 `json:"base"`
	Exponent float64 `json:"exponent"`
}

// Result defines model for Result.
type Result struct {
	Result float64 `json:"result"`
}

// UnaryOperandRequest defines model for UnaryOperandRequest.
type UnaryOperandRequest struct {
	A float64 `json:"a"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// ResultResponse defines model for ResultResponse.
type ResultResponse = Result

// AddJSONRequestBody defines body for Add for application/json ContentType.
type AddJSONRequestBody = BinaryOperandsRequest

// DivideJSONRequestBody defines body for Divide for application/json ContentType.
type DivideJSONRequestBody = BinaryOperandsRequest

// MultiplyJSONRequestBody defines body for Multiply for application/json ContentType.
type MultiplyJSONRequestBody = BinaryOperandsRequest

// PercentageJSONRequestBody defines body for Percentage for application/json ContentType.
type PercentageJSONRequestBody = BinaryOperandsRequest

// PowerJSONRequestBody defines body for Power for application/json ContentType.
type PowerJSONRequestBody = PowerRequest

// SqrtJSONRequestBody defines body for Sqrt for application/json ContentType.
type SqrtJSONRequestBody = UnaryOperandRequest

// SubtractJSONRequestBody defines body for Subtract for application/json ContentType.
type SubtractJSONRequestBody = BinaryOperandsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Add two numbers
	// (POST /add)
	Add(w http.ResponseWriter, r *http.Request)
	// Divide a by b
	// (POST /divide)
	Divide(w http.ResponseWriter, r *http.Request)
	// Liveness check
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Multiply two numbers
	// (POST /multiply)
	Multiply(w http.ResponseWriter, r *http.Request)
	// a percent of b (a% of b)
	// (POST /percentage)
	Percentage(w http.ResponseWriter, r *http.Request)
	// Raise base to exponent
	// (POST /power)
	Power(w http.ResponseWriter, r *http.Request)
	// Square root of a
	// (POST /sqrt)
	Sqrt(w http.ResponseWriter, r *http.Request)
	// Subtract b from a
	// (POST /subtract)
	Subtract(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Add two numbers
// (POST /add)
func (_ Unimplemented) Add(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Divide a by b
// (POST /divide)
func (_ Unimplemented) Divide(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness check
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Multiply two numbers
// (POST /multiply)
func (_ Unimplemented) Multiply(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// a percent of b (a% of b)
// (POST /percentage)
func (_ Unimplemented) Percentage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Raise base to exponent
// (POST /power)
func (_ Unimplemented) Power(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Square root of a
// (POST /sqrt)
func (_ Unimplemented) Sqrt(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Subtract b from a
// (POST /subtract)
func (_ Unimplemented) Subtract(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Add operation middleware
func (siw *ServerInterfaceWrapper) Add(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Add(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Divide operation middleware
func (siw *ServerInterfaceWrapper) Divide(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Divide(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Multiply operation middleware
func (siw *ServerInterfaceWrapper) Multiply(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Multiply(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Percentage operation middleware
func (siw *ServerInterfaceWrapper) Percentage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Percentage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Power operation middleware
func (siw *ServerInterfaceWrapper) Power(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Power(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Sqrt operation middleware
func (siw *ServerInterfaceWrapper) Sqrt(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Sqrt(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Subtract operation middleware
func (siw *ServerInterfaceWrapper) Subtract(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Subtract(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/add", wrapper.Add)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/divide", wrapper.Divide)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/multiply", wrapper.Multiply)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/percentage", wrapper.Percentage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/power", wrapper.Power)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sqrt", wrapper.Sqrt)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subtract", wrapper.Subtract)
	})

	return r
}

type ErrorResponseJSONResponse Error

type ResultResponseJSONResponse Result

type AddRequestObject struct {
	Body *AddJSONRequestBody
}

type AddResponseObject interface {
	VisitAddResponse(w http.ResponseWriter) error
}

type Add200JSONResponse struct{ ResultResponseJSONResponse }

func (response Add200JSONResponse) VisitAddResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Add400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Add400JSONResponse) VisitAddResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DivideRequestObject struct {
	Body *DivideJSONRequestBody
}

type DivideResponseObject interface {
	VisitDivideResponse(w http.ResponseWriter) error
}

type Divide200JSONResponse struct{ ResultResponseJSONResponse }

func (response Divide200JSONResponse) VisitDivideResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Divide400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Divide400JSONResponse) VisitDivideResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Divide422JSONResponse Error

func (response Divide422JSONResponse) VisitDivideResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthStatus

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MultiplyRequestObject struct {
	Body *MultiplyJSONRequestBody
}

type MultiplyResponseObject interface {
	VisitMultiplyResponse(w http.ResponseWriter) error
}

type Multiply200JSONResponse struct{ ResultResponseJSONResponse }

func (response Multiply200JSONResponse) VisitMultiplyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Multiply400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Multiply400JSONResponse) VisitMultiplyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PercentageRequestObject struct {
	Body *PercentageJSONRequestBody
}

type PercentageResponseObject interface {
	VisitPercentageResponse(w http.ResponseWriter) error
}

type Percentage200JSONResponse struct{ ResultResponseJSONResponse }

func (response Percentage200JSONResponse) VisitPercentageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Percentage400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Percentage400JSONResponse) VisitPercentageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PowerRequestObject struct {
	Body *PowerJSONRequestBody
}

type PowerResponseObject interface {
	VisitPowerResponse(w http.ResponseWriter) error
}

type Power200JSONResponse struct{ ResultResponseJSONResponse }

func (response Power200JSONResponse) VisitPowerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Power400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Power400JSONResponse) VisitPowerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SqrtRequestObject struct {
	Body *SqrtJSONRequestBody
}

type SqrtResponseObject interface {
	VisitSqrtResponse(w http.ResponseWriter) error
}

type Sqrt200JSONResponse struct{ ResultResponseJSONResponse }

func (response Sqrt200JSONResponse) VisitSqrtResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Sqrt400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Sqrt400JSONResponse) VisitSqrtResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Sqrt422JSONResponse Error

func (response Sqrt422JSONResponse) VisitSqrtResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type SubtractRequestObject struct {
	Body *SubtractJSONRequestBody
}

type SubtractResponseObject interface {
	VisitSubtractResponse(w http.ResponseWriter) error
}

type Subtract200JSONResponse struct{ ResultResponseJSONResponse }

func (response Subtract200JSONResponse) VisitSubtractResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Subtract400JSONResponse struct{ ErrorResponseJSONResponse }

func (response Subtract400JSONResponse) VisitSubtractResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Add two numbers
	// (POST /add)
	Add(ctx context.Context, request AddRequestObject) (AddResponseObject, error)
	// Divide a by b
	// (POST /divide)
	Divide(ctx context.Context, request DivideRequestObject) (DivideResponseObject, error)
	// Liveness check
	// (GET /healthz)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Multiply two numbers
	// (POST /multiply)
	Multiply(ctx context.Context, request MultiplyRequestObject) (MultiplyResponseObject, error)
	// a percent of b (a% of b)
	// (POST /percentage)
	Percentage(ctx context.Context, request PercentageRequestObject) (PercentageResponseObject, error)
	// Raise base to exponent
	// (POST /power)
	Power(ctx context.Context, request PowerRequestObject) (PowerResponseObject, error)
	// Square root of a
	// (POST /sqrt)
	Sqrt(ctx context.Context, request SqrtRequestObject) (SqrtResponseObject, error)
	// Subtract b from a
	// (POST /subtract)
	Subtract(ctx context.Context, request SubtractRequestObject) (SubtractResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Add operation middleware
func (sh *strictHandler) Add(w http.ResponseWriter, r *http.Request) {
	var request AddRequestObject

	var body AddJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Add(ctx, request.(AddRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Add")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddResponseObject); ok {
		if err := validResponse.VisitAddResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Divide operation middleware
func (sh *strictHandler) Divide(w http.ResponseWriter, r *http.Request) {
	var request DivideRequestObject

	var body DivideJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Divide(ctx, request.(DivideRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Divide")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DivideResponseObject); ok {
		if err := validResponse.VisitDivideResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Multiply operation middleware
func (sh *strictHandler) Multiply(w http.ResponseWriter, r *http.Request) {
	var request MultiplyRequestObject

	var body MultiplyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Multiply(ctx, request.(MultiplyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Multiply")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MultiplyResponseObject); ok {
		if err := validResponse.VisitMultiplyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Percentage operation middleware
func (sh *strictHandler) Percentage(w http.ResponseWriter, r *http.Request) {
	var request PercentageRequestObject

	var body PercentageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Percentage(ctx, request.(PercentageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Percentage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PercentageResponseObject); ok {
		if err := validResponse.VisitPercentageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Power operation middleware
func (sh *strictHandler) Power(w http.ResponseWriter, r *http.Request) {
	var request PowerRequestObject

	var body PowerJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Power(ctx, request.(PowerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Power")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PowerResponseObject); ok {
		if err := validResponse.VisitPowerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Sqrt operation middleware
func (sh *strictHandler) Sqrt(w http.ResponseWriter, r *http.Request) {
	var request SqrtRequestObject

	var body SqrtJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Sqrt(ctx, request.(SqrtRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Sqrt")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SqrtResponseObject); ok {
		if err := validResponse.VisitSqrtResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Subtract operation middleware
func (sh *strictHandler) Subtract(w http.ResponseWriter, r *http.Request) {
	var request SubtractRequestObject

	var body SubtractJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Subtract(ctx, request.(SubtractRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Subtract")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubtractResponseObject); ok {
		if err := validResponse.VisitSubtractResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yWX2/bNhDAvwpx24ANMCw37ZPe2m7AAqxYkGBPRR5O5NlmK5HMkXTrBvruA0nZiWNZ",
	"yLYEGNC8SeT9/d3xyFuQtnPWkAke6ltg8s4aT/nnN2bLl8NKWpDWBDIhfaJzrZYYtDXVJ29NWvNyTR2m",
	"rx+ZllDDD9Wd9ars+ipbhb7vZ6DIS9YuGYEazs0GW62ENi4G6GdwST624ckDKGbHIriKUpL3y9gKia2M",
	"bTYPSXBQTrbfaYO8/dMRo1H+km4i+RySY+uIgy70chxLyx0GqEHZ2LQEMwhbR1CDiV1DnLJsHiXXz4Dp",
	"JmomBfVHQEiK13sx23wimaEVvEfR0G55UPCBtVkd2S1iY3Z/J2zD+ipgiP7YvN+v01fsXJt1P9+lccLd",
	"oDbm78J+IT4Jt8HSEI/gS19LA/wbzNnNPRNjgQ7tdBQi79f/qddBc8zZX/da7z923lFHHftLMtosbbJ3",
	"eFI+aMnWE2+0JJHweG1WokGvpUCjBKoNGklKIOuw7ihoKVKI+UD5eYpGh9wl74eDZlm8vTiHGWyIfXHy",
	"ar6YL1LW1pFBp6GG1/PF/DXMwGFY51wrVCoTsIXE3sm5ghreKgUlTfLhnVXbJxsi40OgP6QaOFJeuDdU",
	"zxaLU7b3ctWDydfP4M1j1A4Hdh5bseuQtwWFCF+sKOX3qQK48qnycl8BuE46ldIbreg01V/L/vcLdgZv",
	"zs6e/0JMnNNREM1WfCO2DypayiAwbTdT9Vzn0f0txbGikXqW0f5+TfIzjEN9kjwPbpCx23cYJ9qLEvH2",
	"QcJ/6A0Z8l7IIdRdxh0FHHLtYhu0a7enu/fDTuJlMGSqOx6PnQ6OWJIJuJqYEBd3Mi+UM2UUAzdhl6IR",
	"P+NP+eOXSdLpCTQBOW8/D9+D19f/GOslak/p3UEiWLF/p01A9TccTjO9SrvPg3Ts6fZdXmtXNxGZBFub",
	"D4OhFQa9IXHvYXpX4AfCOFna2ARGOVXencTLVCp0Bx6iEUu23QTepEac3uZQf7yFyC3UUKHT1eYV9Nf9",
	"3wEAAP//AxyrLUkQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
