/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Microservice exposing basic and advanced arithmetic operations.
 * OpenAPI spec version: 1.0.0
 */
import type { Error } from './error'

/**
 * Invalid input
 */
export type ErrorResponseResponse = Error
