/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Microservice exposing basic and advanced arithmetic operations.
 * OpenAPI spec version: 1.0.0
 */
import type { Result } from './result'

/**
 * Successful calculation
 */
export type ResultResponseResponse = Result
