/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Calculator API
 * Microservice exposing basic and advanced arithmetic operations.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import type {
  BinaryOperandsRequest,
  Error,
  ErrorResponseResponse,
  PowerRequest,
  ResultResponseResponse,
  UnaryOperandRequest,
} from '../models'

import { faker } from '@faker-js/faker'

import { HttpResponse, http } from 'msw'
import type { RequestHandlerOptions } from 'msw'

import { mutator } from '../mutator/index'
import type { ErrorType, BodyType } from '../mutator/index'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getAddUrl = () => {
  return `/add`
}

/**
 * @summary Add two numbers
 */
export const add = async (
  binaryOperandsRequest: BinaryOperandsRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getAddUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(binaryOperandsRequest),
  })
}

export const getAddMutationOptions = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof add>>,
    TError,
    { data: BodyType<BinaryOperandsRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof add>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  const mutationKey = ['add']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof add>>,
    { data: BodyType<BinaryOperandsRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return add(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AddMutationResult = NonNullable<Awaited<ReturnType<typeof add>>>
export type AddMutationBody = BodyType<BinaryOperandsRequest>
export type AddMutationError = ErrorType<ErrorResponseResponse>

/**
 * @summary Add two numbers
 */
export const useAdd = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof add>>,
      TError,
      { data: BodyType<BinaryOperandsRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof add>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  return useMutation(getAddMutationOptions(options), queryClient)
}
export const getDivideUrl = () => {
  return `/divide`
}

/**
 * @summary Divide a by b
 */
export const divide = async (
  binaryOperandsRequest: BinaryOperandsRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getDivideUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(binaryOperandsRequest),
  })
}

export const getDivideMutationOptions = <
  TError = ErrorType<ErrorResponseResponse | Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof divide>>,
    TError,
    { data: BodyType<BinaryOperandsRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof divide>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  const mutationKey = ['divide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof divide>>,
    { data: BodyType<BinaryOperandsRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return divide(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DivideMutationResult = NonNullable<
  Awaited<ReturnType<typeof divide>>
>
export type DivideMutationBody = BodyType<BinaryOperandsRequest>
export type DivideMutationError = ErrorType<ErrorResponseResponse | Error>

/**
 * @summary Divide a by b
 */
export const useDivide = <
  TError = ErrorType<ErrorResponseResponse | Error>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof divide>>,
      TError,
      { data: BodyType<BinaryOperandsRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof divide>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  return useMutation(getDivideMutationOptions(options), queryClient)
}
export const getMultiplyUrl = () => {
  return `/multiply`
}

/**
 * @summary Multiply two numbers
 */
export const multiply = async (
  binaryOperandsRequest: BinaryOperandsRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getMultiplyUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(binaryOperandsRequest),
  })
}

export const getMultiplyMutationOptions = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof multiply>>,
    TError,
    { data: BodyType<BinaryOperandsRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof multiply>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  const mutationKey = ['multiply']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof multiply>>,
    { data: BodyType<BinaryOperandsRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return multiply(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MultiplyMutationResult = NonNullable<
  Awaited<ReturnType<typeof multiply>>
>
export type MultiplyMutationBody = BodyType<BinaryOperandsRequest>
export type MultiplyMutationError = ErrorType<ErrorResponseResponse>

/**
 * @summary Multiply two numbers
 */
export const useMultiply = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof multiply>>,
      TError,
      { data: BodyType<BinaryOperandsRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof multiply>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  return useMutation(getMultiplyMutationOptions(options), queryClient)
}
export const getPercentageUrl = () => {
  return `/percentage`
}

/**
 * @summary a percent of b (a% of b)
 */
export const percentage = async (
  binaryOperandsRequest: BinaryOperandsRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getPercentageUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(binaryOperandsRequest),
  })
}

export const getPercentageMutationOptions = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof percentage>>,
    TError,
    { data: BodyType<BinaryOperandsRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof percentage>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  const mutationKey = ['percentage']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof percentage>>,
    { data: BodyType<BinaryOperandsRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return percentage(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PercentageMutationResult = NonNullable<
  Awaited<ReturnType<typeof percentage>>
>
export type PercentageMutationBody = BodyType<BinaryOperandsRequest>
export type PercentageMutationError = ErrorType<ErrorResponseResponse>

/**
 * @summary a percent of b (a% of b)
 */
export const usePercentage = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof percentage>>,
      TError,
      { data: BodyType<BinaryOperandsRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof percentage>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  return useMutation(getPercentageMutationOptions(options), queryClient)
}
export const getPowerUrl = () => {
  return `/power`
}

/**
 * @summary Raise base to exponent
 */
export const power = async (
  powerRequest: PowerRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getPowerUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(powerRequest),
  })
}

export const getPowerMutationOptions = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof power>>,
    TError,
    { data: BodyType<PowerRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof power>>,
  TError,
  { data: BodyType<PowerRequest> },
  TContext
> => {
  const mutationKey = ['power']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof power>>,
    { data: BodyType<PowerRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return power(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PowerMutationResult = NonNullable<Awaited<ReturnType<typeof power>>>
export type PowerMutationBody = BodyType<PowerRequest>
export type PowerMutationError = ErrorType<ErrorResponseResponse>

/**
 * @summary Raise base to exponent
 */
export const usePower = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof power>>,
      TError,
      { data: BodyType<PowerRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof power>>,
  TError,
  { data: BodyType<PowerRequest> },
  TContext
> => {
  return useMutation(getPowerMutationOptions(options), queryClient)
}
export const getSqrtUrl = () => {
  return `/sqrt`
}

/**
 * @summary Square root of a
 */
export const sqrt = async (
  unaryOperandRequest: UnaryOperandRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getSqrtUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(unaryOperandRequest),
  })
}

export const getSqrtMutationOptions = <
  TError = ErrorType<ErrorResponseResponse | Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sqrt>>,
    TError,
    { data: BodyType<UnaryOperandRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof sqrt>>,
  TError,
  { data: BodyType<UnaryOperandRequest> },
  TContext
> => {
  const mutationKey = ['sqrt']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sqrt>>,
    { data: BodyType<UnaryOperandRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return sqrt(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SqrtMutationResult = NonNullable<Awaited<ReturnType<typeof sqrt>>>
export type SqrtMutationBody = BodyType<UnaryOperandRequest>
export type SqrtMutationError = ErrorType<ErrorResponseResponse | Error>

/**
 * @summary Square root of a
 */
export const useSqrt = <
  TError = ErrorType<ErrorResponseResponse | Error>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sqrt>>,
      TError,
      { data: BodyType<UnaryOperandRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sqrt>>,
  TError,
  { data: BodyType<UnaryOperandRequest> },
  TContext
> => {
  return useMutation(getSqrtMutationOptions(options), queryClient)
}
export const getSubtractUrl = () => {
  return `/subtract`
}

/**
 * @summary Subtract b from a
 */
export const subtract = async (
  binaryOperandsRequest: BinaryOperandsRequest,
  options?: Parameters<typeof mutator>[1],
): Promise<ResultResponseResponse> => {
  return mutator<ResultResponseResponse>(getSubtractUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(binaryOperandsRequest),
  })
}

export const getSubtractMutationOptions = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subtract>>,
    TError,
    { data: BodyType<BinaryOperandsRequest> },
    TContext
  >
  request?: SecondParameter<typeof mutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof subtract>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  const mutationKey = ['subtract']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subtract>>,
    { data: BodyType<BinaryOperandsRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return subtract(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SubtractMutationResult = NonNullable<
  Awaited<ReturnType<typeof subtract>>
>
export type SubtractMutationBody = BodyType<BinaryOperandsRequest>
export type SubtractMutationError = ErrorType<ErrorResponseResponse>

/**
 * @summary Subtract b from a
 */
export const useSubtract = <
  TError = ErrorType<ErrorResponseResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof subtract>>,
      TError,
      { data: BodyType<BinaryOperandsRequest> },
      TContext
    >
    request?: SecondParameter<typeof mutator>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof subtract>>,
  TError,
  { data: BodyType<BinaryOperandsRequest> },
  TContext
> => {
  return useMutation(getSubtractMutationOptions(options), queryClient)
}

export const getAddResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getDivideResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getMultiplyResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getPercentageResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getPowerResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getSqrtResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getSubtractResponseMock = (
  overrideResponse: Partial<Extract<ResultResponseResponse, object>> = {},
): ResultResponseResponse => ({
  result: faker.number.float({ fractionDigits: 2 }),
  ...overrideResponse,
})

export const getAddMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/add',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getAddResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getDivideMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/divide',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getDivideResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getMultiplyMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/multiply',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getMultiplyResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPercentageMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/percentage',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getPercentageResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getPowerMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/power',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getPowerResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getSqrtMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/sqrt',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSqrtResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}

export const getSubtractMockHandler = (
  overrideResponse?:
    | ResultResponseResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultResponseResponse> | ResultResponseResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/subtract',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSubtractResponseMock(),
        { status: 200 },
      )
    },
    options,
  )
}
export const getCalculatorMock = () => [
  getAddMockHandler(),
  getDivideMockHandler(),
  getMultiplyMockHandler(),
  getPercentageMockHandler(),
  getPowerMockHandler(),
  getSqrtMockHandler(),
  getSubtractMockHandler(),
]
